### ISSUE TITLE
`component.evidence` is repeated in proto and object in jsonschema

### ISSUE THREAD

**Issue by prabhu** [CycloneDX/specification#422] opened 2024-04-09 16:03 UTC
Looks like this got missed somehow

I think it must be `optional` in the proto as well.

https://github.com/CycloneDX/specification/blob/master/schema/bom-1.6.proto#L136

https://github.com/CycloneDX/specification/blob/master/schema/bom-1.6.schema.json#L2079

Originally reported [here](https://github.com/CycloneDX/specification/issues/272#issuecomment-1868576165)

**Comment by jkowalleck** [comment] 2024-04-09 16:12
confirmed.

in ProtoBuf is it a repeated (optional) element: https://github.com/CycloneDX/specification/blob/55343ba19dee1785acf1ce9191540d5fd7b590db/schema/bom-1.6.proto#L135-L136

in JSON it is a single optional element: https://github.com/CycloneDX/specification/blob/55343ba19dee1785acf1ce9191540d5fd7b590db/schema/bom-1.6.schema.json#L1061-L1065
in XML ti is a single optional element: https://github.com/CycloneDX/specification/blob/55343ba19dee1785acf1ce9191540d5fd7b590db/schema/bom-1.6.xsd#L680-L684



i agree, there is a difference.

**Comment by jkowalleck** [comment] 2024-04-09 16:14
https://github.com/CycloneDX/specification/issues/272#issuecomment-1869972139
> Actually, the defect is in the JSON and XML schemas. In this case, the protobuf is correct. Identity should be an array.

**Comment by jkowalleck** [comment] 2024-04-09 16:15
@stevespringett so we make the JSON/XML being a list?

**Comment by prabhu** [comment] 2024-04-09 16:16
@jkowalleck I thought only evidence.identity becomes an array, while evidence continued to be an object.

**Comment by jkowalleck** [comment] 2024-04-11 16:33
> @jkowalleck I thought only evidence.identity becomes an array, while evidence continued to be an object.

i see.
proposed a PR to fix it: https://github.com/CycloneDX/specification/pull/425

**Comment by jkowalleck** [comment] 2024-09-04 13:14
fixed via https://github.com/CycloneDX/specification/pull/517

**Comment by jkowalleck** [comment] 2024-11-04 10:23
reopened. 

we are currently  re-evaluating the protobuf BC detection -- #532

this leads to be opportunity to consider https://github.com/CycloneDX/specification/pull/425 a non-breaking change.
Which might lead to the opportunity to make the `repeated` field an `optioanl` field instead, as it was intended.

**Closed** 2024-11-07 14:04 UTC
Labels: defect, validated, CDX 1.6, format: ProtoBuf
