### ISSUE TITLE
Manufacturer spelling error?

### ISSUE THREAD

**Issue by elear** [CycloneDX/specification#126] opened 2022-01-21 13:53 UTC
Version 1.4:

Around line 141 the schema uses "manufacture" and note "manufacturer".  Was this intentional?  The description would lead one to believe that it is an error.

**Comment by stevespringett** [comment] 2022-01-21 16:10
Indeed, it is misspelled and is an unfortunate mistake along the same lines as http "referer".

Duplicate of #57

**Comment by elear** [comment] 2022-01-21 16:29
Ok then.  Should be closed as a dup?

**Closed** 2023-01-22 22:02 UTC
Labels: question
